### ISSUE TITLE
1.19.2 Certain enchantments missing from JEI/creative menu

### ISSUE THREAD

**Issue by Illios42** [daedalus4096/PrimalMagick#156]
While testing around, I noticed multiple enchantments (e.g. Bounty, Judgement, etc) not being a part of the creative menu or the menu of a mod like JEI. That makes it incredibly hard to check for the highest enchantment level, what items it can be used on theoretically etc. and seems like an oversight to me as a few of them do show up in the correct tab like Magick Protection.
I tested this on version 3.2.1 and would appreciate seeing this addressed, at least, in a future version if not for 1.19.

**Comment by daedalus4096** [comment]
This was originally intended behavior, to prevent confusion when players would come across a special enchantment from the mod, such as those attained through ritual enhancement of tools, and not have any indication what it does.  With the improvements to enchantment descriptions since original implementation, however, I believe this is no longer necessary.  These enchantments will now be allowed on books (but still not from villager trades) in the next build, tentatively v4.0.3.  Thank you for the report.
