### ISSUE TITLE
Null Affinity crashes game?

### ISSUE THREAD

**Issue by darrenh2** [daedalus4096/PrimalMagick#227]
I'm not real good at reading crash logs but I think the OutOfBoundsException error I'm getting is related to the affinity manager possibly getting a null value for an item - happens on nether cheese from Rats Mod and the fruit from Roots Classic mod. The crash report only mentions the OutofBounds error but the ATLauncher log shows the AffinityManager issues.

[crash-2023-11-08_05.47.37-client.txt](https://github.com/daedalus4096/PrimalMagick/files/13297403/crash-2023-11-08_05.47.37-client.txt)

ATL Log:
[ATL_log.txt](https://github.com/daedalus4096/PrimalMagick/files/13297445/ATL_log.txt)

**Comment by daedalus4096** [comment]
Thanks for the report.  This is most curious, and the log seems to indicate there's a lot going on.  When exactly does the crash occur?  When holding Shift over an item stack in your inventory to view its affinities?  Or some other time?

**Comment by darrenh2** [comment]
It happens when I mouse over the item, not even holding shift..usually I can see the affinities when I mouse over the item - most time says unknown or none

**Comment by daedalus4096** [comment]
I wasn't able to reproduce this locally, but I added some null guards at the suspect part of the code.  Hopefully that means its fixed in the next release, currently planned as v4.0.8.  If you encounter it again, please open a new ticket with fresh logs.  Thank you again for the bug report and helping make the mod better!
