### ISSUE TITLE
[Crash] Treefolk fertilizing Regions Unexplored Alpha Grass 

### ISSUE THREAD

**Issue by Fiamat** [daedalus4096/PrimalMagick#274]
When the treefolk fertilizes Alpha Grass from Regions Unexplored it oftentimes results in a crash. Using Primal Magick 4.0.9 and RU 0.5.5 (both newest at the time of writing). Tested on both multiplayer server and singleplayer world. No such situation happens when I use bonemeal on the Alpha Grass (often Alpha Grass requires more than one bonemeal to produce anything and does not create grass around the given block; maybe there's the problem).

**Steps to reproduce:**
1) Create/find a patch of Alpha Grass from Regions Unexplored.
2) Spawn a treefolk and wait for it to fertilize the terrain (possibly more than once; occasionally works as intended)

**Result:**
- crash

**Expected result:**
- behavior analogous to a single/multiple (?) application/s of a bonemeal

**Crash log:**
[crash-2024-07-03_13.06.07-server.txt](https://github.com/user-attachments/files/16085483/crash-2024-07-03_13.06.07-server.txt)

**Comment by daedalus4096** [comment]
Thank you for the report. I'll investigate the crash when I get a chance and try to fix the underlying issue. In the meantime, you should be able to work around this by using a datapack to add the Alpha Grass to the "treefolk_fertilize_exempt" tag, which you can find in /data/primalmagick/tags/blocks.

**Comment by Fiamat** [comment]
That's a neat and clean workaround, thank you and good luck!

**Comment by daedalus4096** [comment]
I've done some investigating, and I don't believe the root cause of this bug to be on Primal Magick's side. I could always be wrong, but nothing is jumping out at me. As such, I've reported the bug to the authors of Regions Unexplored and added Alpha Grass to the treefolks' base "do not fertilize" list to prevent the issue from happening further in the wild. Thank you for the report!
