### ISSUE TITLE
Provide path for greater level enchantments through Primal Magick

### ISSUE THREAD

**Issue by Shocktrooper** [daedalus4096/PrimalMagick#68]
As a plus you can add extra enchantments onto items but as you progress more into the mod it would be nice to be able to unlock the ability to enhance the runescribing enchantments past level 1 where applicable to max level.  An idea would be to unlock levels potentially as you go through basic(1), master(2,3), expert(4), Supreme(5)

For instance when adding the punch runescribe it would be nice to be able to vary the level as I see fit from the first level to the last one at level 5 depending on my unlock level of runescribing

**Comment by daedalus4096** [comment]
Perhaps I'm not understanding your request correctly, but what you're describing should already be possible through the use of Power Runes.  Adding a Power Rune to a rune combination in a Runescribing Altar should increase the level of all enchantments being applied by one level, stacking with more power runes to the maximum level of the enchantment(s).  Is this not working for you?

**Comment by Shocktrooper** [comment]
My mistake I see it in the grimoire now.  I did not see that on my first pass and was looking for a separate entry about this.  Potentially this can turn into an enhancement ticket then and have separate slots for power runes so they do not crowd out rune combinations for the base enchantments themselves

**Comment by daedalus4096** [comment]
I'd rather not have special bonus slots for power runes, honestly.  There's supposed to be a trade off for the player between breadth and power of enchantments applied.  Given the control that the runescribing feature provides, especially given that you can runescribe items that have already been enchanted on an enchanting table, I feel that doing otherwise would make the feature overpowered.  Thank you for the suggestion, however.
