### ISSUE TITLE
Allow blocks with inventories to interact with inventory interaction blocs

### ISSUE THREAD

**Issue by Shocktrooper** [daedalus4096/PrimalMagick#71]
As minecraft allows a degree of automation via certain blocks it seems that Primal Magick is missing something that allows any of those blocks to interact with inventories in Primal Magick blocks.  For instance it would be cool to place a vanilla hopper on top&side of the calcinator to feed fuel and items in to calcinate and a hopper on the bottom or other side to take dust/crystals out.

**Comment by daedalus4096** [comment]
This should already be possible.  I haven't tested with other mods' pipes and the like, but I know that hoppers at one point worked as you describe.  If they don't now, that's a bug.  What versions of MC, Forge, and PM are you playing on now?

**Comment by Shocktrooper** [comment]
I just tested this with forge version 39.0.10 and 2.0.3 of primal magick.  It appears that at least the calcinator can not be fed fuel/input blocks with the vanilla hopper but the vanilla hopper can take finished dush/shards out once processed.  Feeding into primal magick blocks would be nice.  I can test out the other blocks if you would like but for testing purposes I have just tried only the calcinator

**Comment by daedalus4096** [comment]
I did some testing and found that hoppers only partially worked in v2.0.3.  Output from the bottom of calcinators worked as you mentioned.  I also observed that input of materials into the top of the calcinator seemed to be working.  There was, however, a bug in the input of fuel into the sides of calcinators, which has been fixed in v2.0.4.  In short, using a calcinator in the pictured configuration should now work as you requested.  Or, at least, it does for me.  If you encounter any other bugs of this type, please file a new ticket with fresh details.  Thank you for reporting this issue and helping me to make the mod better!

![2022-01-23_16 24 48](https://user-images.githubusercontent.com/1577528/150734812-3ed0c115-d566-4bb9-8f12-2135947937bd.png)
