### ISSUE TITLE
Make blank grimoire entries or hints for missing permanent attunement bonuses

### ISSUE THREAD

**Issue by Shocktrooper** [daedalus4096/PrimalMagick#74]
Breakout a part of #70 which was a dual ticket.

Without any modifiers like ambrosia it appears that permanent attunements get to varying degrees throughout the game with in endgame the permanent attunements being at varying values.  If there are more ways to get permanent attunement it would be a nice enhancement to have the grimoire have hints and blank entries for what things would increase permanent attunement

**Comment by daedalus4096** [comment]
Permanent attunement currently only comes from completing research entries, and I was more concerned with having sensible attunement values for appropriate research than I was with making them all come out to the same value at endgame.  Having them all come out to the same value isn't really feasible anyway, at least not if I want to add new content to the mod down the road, which I'd like to do.  I'd have to rebalance them all every time I added a new attunement-granted research entry, which would be a nightmare.

Maybe in the future I'll add something like a dungeon loot item which can grant a permanent attunement bonus.  I've added it to my internal roadmap so that I don't forget about the idea, but that's outside the scope of this ticket.
