### ISSUE TITLE
Marble Gen cant be disabled

### ISSUE THREAD

**Issue by Peach774** [daedalus4096/PrimalMagick#75]
As title - you cant disable marble generation in the config, so if you have other marble already generating, you now have 2 types

**Comment by daedalus4096** [comment]
At the moment, Primal Magick doesn't recognize marble from other mods as a valid construction material for its recipes; they're not currently interchangeable.  Thus, disabling the mod's marble generation would be crippling to players' ability to progress.  What other mods are generating marble that you wish to de-duplicate?

**Comment by Peach774** [comment]
Blue power is one, but this should also be an easy fix right? Couldn't Primal Magick just use the forge:marble tag wherever it uses marble in its recipes?

**Comment by daedalus4096** [comment]
To my knowledge, there is no forge:marble tag.  At least, it's not one of the standard Forge tags and Blue Power doesn't define it.  Still, I suppose I could add a config file option to disable worldgen of my mod's marble with some appropriate warning tags, so that people who know what they're doing can tinker with it at their own risk.

**Comment by daedalus4096** [comment]
The next release of the mod, planned as v2.0.5, will have an option in its primalmagick-common.toml config file that should do this.  It's called "generateMarble" and when set to false, marble should not be generated in the world, with the exception of shrines.  If you find this is not working, please file a new ticket.  Thanks for your suggestion to help make the mod better!
