### ISSUE TITLE
Absorption effect are permanent from healing spells

### ISSUE THREAD

**Issue by Tonomo** [daedalus4096/PrimalMagick#91]
When having two different healing spells on a sun wand and using both spells right after each other will result in the first spells absorption effect (Golden hearts) to stay permanently until damage removes them.

How to do bug:
1. Have two healing spells on a sunwand.
2. Use one healing spell.
3. Use the other healing spell while the absoprtion effect duration is still counting down.
4. Now you have permanent absorption from the first healing spell.

Note:
One of my healing spells had a power modifier while the other spell lacked any modifier.
Bug might work with scrolls and other means of healing, this have not been tested.

**Comment by daedalus4096** [comment]
It turns out this is actually a long-standing bug in Vanilla: https://bugs.mojang.com/browse/MC-182497.  It doesn't come up much there because absorbs are such an uncommon effect, but Primal Magick healing spells make it a much bigger issue.  Until Mojang fixes the bug on their side, I've added a check that prevents healing spells from applying their absorb if a larger absorb is already present.  This should prevent the more common error case you describe, but it's still possible to reproduce with the help of items like Golden Apples; I don't know of a way to prevent this.  This change will be available in the upcoming v2.1.1 release.  Thank you for the report and helping to make the mod better!
